### ISSUE TITLE
prompt store 希望可以添加点击直接添加到聊天窗口重

### ISSUE THREAD

**Issue by yh4922** [pljhonglu/ChatGPT-T#2]
提一个建议 
prompt store 点击的时候 可以创建一个新的聊天 自动添加到聊天窗口

**Comment by pljhonglu** [comment]
添加 prompt 之后，在聊天窗口使用 / 命令可以直接选择哈。
![image](https://user-images.githubusercontent.com/2472557/226548022-d03865dd-3b79-4b78-bbea-9b6c4fdbad15.png)
