### ISSUE TITLE
一个对话轮数太多，就提示Request Error: 400

### ISSUE THREAD

**Issue by absir1949** [pljhonglu/ChatGPT-T#3]
一个聊天如果太多轮数，就会提示Request Error: 400，重试也无法解决。
<img width="434" alt="image" src="https://user-images.githubusercontent.com/14873265/226612861-c97ebe85-61a7-4b42-ab24-7be3b0ff5c5e.png">

这个时候去别的聊天，功能返回正常。
<img width="437" alt="image" src="https://user-images.githubusercontent.com/14873265/226612759-effa5eda-379a-4bd1-a4cf-6c0d2d85be88.png">

**Comment by pljhonglu** [comment]
https://github.com/pljhonglu/ChatGPT-T/releases
